//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "UserCalib", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.User), "Calib", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.Calib))]
[assembly: EdmRelationshipAttribute("Model", "UserData_10MV", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.User), "Data_10MV", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.Data_10MV))]
[assembly: EdmRelationshipAttribute("Model", "UserDATA_15MV", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.User), "DATA_15MV", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.DATA_15MV))]
[assembly: EdmRelationshipAttribute("Model", "UserT_P_CorrSet", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.User), "T_P_CorrSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.T_P_CorrSet))]
[assembly: EdmRelationshipAttribute("Model", "UserData_18MV", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.User), "Data_18MV", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.Data_18MV))]
[assembly: EdmRelationshipAttribute("Model", "UserData_6MV", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.User), "Data_6MV", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.Data_6MV))]
[assembly: EdmRelationshipAttribute("Model", "UserQA_Data", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.User), "QA_Data", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.QA_Data))]

#endregion

namespace ClassLibrary1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Calib> Calibs
        {
            get
            {
                if ((_Calibs == null))
                {
                    _Calibs = base.CreateObjectSet<Calib>("Calibs");
                }
                return _Calibs;
            }
        }
        private ObjectSet<Calib> _Calibs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Data_10MV> Data_10MV
        {
            get
            {
                if ((_Data_10MV == null))
                {
                    _Data_10MV = base.CreateObjectSet<Data_10MV>("Data_10MV");
                }
                return _Data_10MV;
            }
        }
        private ObjectSet<Data_10MV> _Data_10MV;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DATA_15MV> DATA_15MV
        {
            get
            {
                if ((_DATA_15MV == null))
                {
                    _DATA_15MV = base.CreateObjectSet<DATA_15MV>("DATA_15MV");
                }
                return _DATA_15MV;
            }
        }
        private ObjectSet<DATA_15MV> _DATA_15MV;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Data_18MV> Data_18MV
        {
            get
            {
                if ((_Data_18MV == null))
                {
                    _Data_18MV = base.CreateObjectSet<Data_18MV>("Data_18MV");
                }
                return _Data_18MV;
            }
        }
        private ObjectSet<Data_18MV> _Data_18MV;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Data_6MV> Data_6MV
        {
            get
            {
                if ((_Data_6MV == null))
                {
                    _Data_6MV = base.CreateObjectSet<Data_6MV>("Data_6MV");
                }
                return _Data_6MV;
            }
        }
        private ObjectSet<Data_6MV> _Data_6MV;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QA_Data> QA_Data
        {
            get
            {
                if ((_QA_Data == null))
                {
                    _QA_Data = base.CreateObjectSet<QA_Data>("QA_Data");
                }
                return _QA_Data;
            }
        }
        private ObjectSet<QA_Data> _QA_Data;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_P_CorrSet> T_P_CorrSet
        {
            get
            {
                if ((_T_P_CorrSet == null))
                {
                    _T_P_CorrSet = base.CreateObjectSet<T_P_CorrSet>("T_P_CorrSet");
                }
                return _T_P_CorrSet;
            }
        }
        private ObjectSet<T_P_CorrSet> _T_P_CorrSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Calibs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCalibs(Calib calib)
        {
            base.AddObject("Calibs", calib);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Data_10MV EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToData_10MV(Data_10MV data_10MV)
        {
            base.AddObject("Data_10MV", data_10MV);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DATA_15MV EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDATA_15MV(DATA_15MV dATA_15MV)
        {
            base.AddObject("DATA_15MV", dATA_15MV);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Data_18MV EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToData_18MV(Data_18MV data_18MV)
        {
            base.AddObject("Data_18MV", data_18MV);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Data_6MV EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToData_6MV(Data_6MV data_6MV)
        {
            base.AddObject("Data_6MV", data_6MV);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QA_Data EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQA_Data(QA_Data qA_Data)
        {
            base.AddObject("QA_Data", qA_Data);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_P_CorrSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_P_CorrSet(T_P_CorrSet t_P_CorrSet)
        {
            base.AddObject("T_P_CorrSet", t_P_CorrSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Calib")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Calib : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Calib object.
        /// </summary>
        /// <param name="calib_ID">Initial value of the Calib_ID property.</param>
        public static Calib CreateCalib(global::System.Guid calib_ID)
        {
            Calib calib = new Calib();
            calib.Calib_ID = calib_ID;
            return calib;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Base_Value_6MV
        {
            get
            {
                return _Base_Value_6MV;
            }
            set
            {
                OnBase_Value_6MVChanging(value);
                ReportPropertyChanging("Base_Value_6MV");
                _Base_Value_6MV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Base_Value_6MV");
                OnBase_Value_6MVChanged();
            }
        }
        private global::System.String _Base_Value_6MV;
        partial void OnBase_Value_6MVChanging(global::System.String value);
        partial void OnBase_Value_6MVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Base_Value_10MV
        {
            get
            {
                return _Base_Value_10MV;
            }
            set
            {
                OnBase_Value_10MVChanging(value);
                ReportPropertyChanging("Base_Value_10MV");
                _Base_Value_10MV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Base_Value_10MV");
                OnBase_Value_10MVChanged();
            }
        }
        private global::System.String _Base_Value_10MV;
        partial void OnBase_Value_10MVChanging(global::System.String value);
        partial void OnBase_Value_10MVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Base_Value_15MV
        {
            get
            {
                return _Base_Value_15MV;
            }
            set
            {
                OnBase_Value_15MVChanging(value);
                ReportPropertyChanging("Base_Value_15MV");
                _Base_Value_15MV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Base_Value_15MV");
                OnBase_Value_15MVChanged();
            }
        }
        private global::System.String _Base_Value_15MV;
        partial void OnBase_Value_15MVChanging(global::System.String value);
        partial void OnBase_Value_15MVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Base_Value_18MV
        {
            get
            {
                return _Base_Value_18MV;
            }
            set
            {
                OnBase_Value_18MVChanging(value);
                ReportPropertyChanging("Base_Value_18MV");
                _Base_Value_18MV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Base_Value_18MV");
                OnBase_Value_18MVChanged();
            }
        }
        private global::System.String _Base_Value_18MV;
        partial void OnBase_Value_18MVChanging(global::System.String value);
        partial void OnBase_Value_18MVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Calib_ID
        {
            get
            {
                return _Calib_ID;
            }
            set
            {
                if (_Calib_ID != value)
                {
                    OnCalib_IDChanging(value);
                    ReportPropertyChanging("Calib_ID");
                    _Calib_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Calib_ID");
                    OnCalib_IDChanged();
                }
            }
        }
        private global::System.Guid _Calib_ID;
        partial void OnCalib_IDChanging(global::System.Guid value);
        partial void OnCalib_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserCalib", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserCalib", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserCalib", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserCalib", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserCalib", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Data_10MV")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Data_10MV : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Data_10MV object.
        /// </summary>
        /// <param name="data_10MV_ID">Initial value of the Data_10MV_ID property.</param>
        public static Data_10MV CreateData_10MV(global::System.Guid data_10MV_ID)
        {
            Data_10MV data_10MV = new Data_10MV();
            data_10MV.Data_10MV_ID = data_10MV_ID;
            return data_10MV;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value1
        {
            get
            {
                return _Value1;
            }
            set
            {
                OnValue1Changing(value);
                ReportPropertyChanging("Value1");
                _Value1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value1");
                OnValue1Changed();
            }
        }
        private global::System.String _Value1;
        partial void OnValue1Changing(global::System.String value);
        partial void OnValue1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value2
        {
            get
            {
                return _Value2;
            }
            set
            {
                OnValue2Changing(value);
                ReportPropertyChanging("Value2");
                _Value2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value2");
                OnValue2Changed();
            }
        }
        private global::System.String _Value2;
        partial void OnValue2Changing(global::System.String value);
        partial void OnValue2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value3
        {
            get
            {
                return _Value3;
            }
            set
            {
                OnValue3Changing(value);
                ReportPropertyChanging("Value3");
                _Value3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value3");
                OnValue3Changed();
            }
        }
        private global::System.String _Value3;
        partial void OnValue3Changing(global::System.String value);
        partial void OnValue3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value4
        {
            get
            {
                return _Value4;
            }
            set
            {
                OnValue4Changing(value);
                ReportPropertyChanging("Value4");
                _Value4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value4");
                OnValue4Changed();
            }
        }
        private global::System.String _Value4;
        partial void OnValue4Changing(global::System.String value);
        partial void OnValue4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Data_10MV_ID
        {
            get
            {
                return _Data_10MV_ID;
            }
            set
            {
                if (_Data_10MV_ID != value)
                {
                    OnData_10MV_IDChanging(value);
                    ReportPropertyChanging("Data_10MV_ID");
                    _Data_10MV_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Data_10MV_ID");
                    OnData_10MV_IDChanged();
                }
            }
        }
        private global::System.Guid _Data_10MV_ID;
        partial void OnData_10MV_IDChanging(global::System.Guid value);
        partial void OnData_10MV_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Delta_10MV
        {
            get
            {
                return _Delta_10MV;
            }
            set
            {
                OnDelta_10MVChanging(value);
                ReportPropertyChanging("Delta_10MV");
                _Delta_10MV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delta_10MV");
                OnDelta_10MVChanged();
            }
        }
        private Nullable<global::System.Double> _Delta_10MV;
        partial void OnDelta_10MVChanging(Nullable<global::System.Double> value);
        partial void OnDelta_10MVChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserData_10MV", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_10MV", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_10MV", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_10MV", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserData_10MV", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="DATA_15MV")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DATA_15MV : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DATA_15MV object.
        /// </summary>
        /// <param name="data_15MV_ID">Initial value of the Data_15MV_ID property.</param>
        public static DATA_15MV CreateDATA_15MV(global::System.Guid data_15MV_ID)
        {
            DATA_15MV dATA_15MV = new DATA_15MV();
            dATA_15MV.Data_15MV_ID = data_15MV_ID;
            return dATA_15MV;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value1
        {
            get
            {
                return _Value1;
            }
            set
            {
                OnValue1Changing(value);
                ReportPropertyChanging("Value1");
                _Value1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value1");
                OnValue1Changed();
            }
        }
        private global::System.String _Value1;
        partial void OnValue1Changing(global::System.String value);
        partial void OnValue1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value2
        {
            get
            {
                return _Value2;
            }
            set
            {
                OnValue2Changing(value);
                ReportPropertyChanging("Value2");
                _Value2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value2");
                OnValue2Changed();
            }
        }
        private global::System.String _Value2;
        partial void OnValue2Changing(global::System.String value);
        partial void OnValue2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value3
        {
            get
            {
                return _Value3;
            }
            set
            {
                OnValue3Changing(value);
                ReportPropertyChanging("Value3");
                _Value3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value3");
                OnValue3Changed();
            }
        }
        private global::System.String _Value3;
        partial void OnValue3Changing(global::System.String value);
        partial void OnValue3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value4
        {
            get
            {
                return _Value4;
            }
            set
            {
                OnValue4Changing(value);
                ReportPropertyChanging("Value4");
                _Value4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value4");
                OnValue4Changed();
            }
        }
        private global::System.String _Value4;
        partial void OnValue4Changing(global::System.String value);
        partial void OnValue4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Data_15MV_ID
        {
            get
            {
                return _Data_15MV_ID;
            }
            set
            {
                if (_Data_15MV_ID != value)
                {
                    OnData_15MV_IDChanging(value);
                    ReportPropertyChanging("Data_15MV_ID");
                    _Data_15MV_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Data_15MV_ID");
                    OnData_15MV_IDChanged();
                }
            }
        }
        private global::System.Guid _Data_15MV_ID;
        partial void OnData_15MV_IDChanging(global::System.Guid value);
        partial void OnData_15MV_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Delta_15MV
        {
            get
            {
                return _Delta_15MV;
            }
            set
            {
                OnDelta_15MVChanging(value);
                ReportPropertyChanging("Delta_15MV");
                _Delta_15MV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delta_15MV");
                OnDelta_15MVChanged();
            }
        }
        private Nullable<global::System.Double> _Delta_15MV;
        partial void OnDelta_15MVChanging(Nullable<global::System.Double> value);
        partial void OnDelta_15MVChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserDATA_15MV", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserDATA_15MV", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserDATA_15MV", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserDATA_15MV", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserDATA_15MV", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Data_18MV")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Data_18MV : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Data_18MV object.
        /// </summary>
        /// <param name="data_18MV_ID">Initial value of the Data_18MV_ID property.</param>
        public static Data_18MV CreateData_18MV(global::System.Guid data_18MV_ID)
        {
            Data_18MV data_18MV = new Data_18MV();
            data_18MV.Data_18MV_ID = data_18MV_ID;
            return data_18MV;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value1
        {
            get
            {
                return _Value1;
            }
            set
            {
                OnValue1Changing(value);
                ReportPropertyChanging("Value1");
                _Value1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value1");
                OnValue1Changed();
            }
        }
        private global::System.String _Value1;
        partial void OnValue1Changing(global::System.String value);
        partial void OnValue1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value2
        {
            get
            {
                return _Value2;
            }
            set
            {
                OnValue2Changing(value);
                ReportPropertyChanging("Value2");
                _Value2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value2");
                OnValue2Changed();
            }
        }
        private global::System.String _Value2;
        partial void OnValue2Changing(global::System.String value);
        partial void OnValue2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value3
        {
            get
            {
                return _Value3;
            }
            set
            {
                OnValue3Changing(value);
                ReportPropertyChanging("Value3");
                _Value3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value3");
                OnValue3Changed();
            }
        }
        private global::System.String _Value3;
        partial void OnValue3Changing(global::System.String value);
        partial void OnValue3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value4
        {
            get
            {
                return _Value4;
            }
            set
            {
                OnValue4Changing(value);
                ReportPropertyChanging("Value4");
                _Value4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value4");
                OnValue4Changed();
            }
        }
        private global::System.String _Value4;
        partial void OnValue4Changing(global::System.String value);
        partial void OnValue4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Data_18MV_ID
        {
            get
            {
                return _Data_18MV_ID;
            }
            set
            {
                if (_Data_18MV_ID != value)
                {
                    OnData_18MV_IDChanging(value);
                    ReportPropertyChanging("Data_18MV_ID");
                    _Data_18MV_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Data_18MV_ID");
                    OnData_18MV_IDChanged();
                }
            }
        }
        private global::System.Guid _Data_18MV_ID;
        partial void OnData_18MV_IDChanging(global::System.Guid value);
        partial void OnData_18MV_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Delta_18MV
        {
            get
            {
                return _Delta_18MV;
            }
            set
            {
                OnDelta_18MVChanging(value);
                ReportPropertyChanging("Delta_18MV");
                _Delta_18MV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delta_18MV");
                OnDelta_18MVChanged();
            }
        }
        private Nullable<global::System.Double> _Delta_18MV;
        partial void OnDelta_18MVChanging(Nullable<global::System.Double> value);
        partial void OnDelta_18MVChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserData_18MV", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_18MV", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_18MV", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_18MV", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserData_18MV", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Data_6MV")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Data_6MV : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Data_6MV object.
        /// </summary>
        /// <param name="data_6MV_ID">Initial value of the Data_6MV_ID property.</param>
        public static Data_6MV CreateData_6MV(global::System.Guid data_6MV_ID)
        {
            Data_6MV data_6MV = new Data_6MV();
            data_6MV.Data_6MV_ID = data_6MV_ID;
            return data_6MV;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value1
        {
            get
            {
                return _Value1;
            }
            set
            {
                OnValue1Changing(value);
                ReportPropertyChanging("Value1");
                _Value1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value1");
                OnValue1Changed();
            }
        }
        private global::System.String _Value1;
        partial void OnValue1Changing(global::System.String value);
        partial void OnValue1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value2
        {
            get
            {
                return _Value2;
            }
            set
            {
                OnValue2Changing(value);
                ReportPropertyChanging("Value2");
                _Value2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value2");
                OnValue2Changed();
            }
        }
        private global::System.String _Value2;
        partial void OnValue2Changing(global::System.String value);
        partial void OnValue2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Valu3
        {
            get
            {
                return _Valu3;
            }
            set
            {
                OnValu3Changing(value);
                ReportPropertyChanging("Valu3");
                _Valu3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Valu3");
                OnValu3Changed();
            }
        }
        private global::System.String _Valu3;
        partial void OnValu3Changing(global::System.String value);
        partial void OnValu3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Valu4
        {
            get
            {
                return _Valu4;
            }
            set
            {
                OnValu4Changing(value);
                ReportPropertyChanging("Valu4");
                _Valu4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Valu4");
                OnValu4Changed();
            }
        }
        private global::System.String _Valu4;
        partial void OnValu4Changing(global::System.String value);
        partial void OnValu4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Data_6MV_ID
        {
            get
            {
                return _Data_6MV_ID;
            }
            set
            {
                if (_Data_6MV_ID != value)
                {
                    OnData_6MV_IDChanging(value);
                    ReportPropertyChanging("Data_6MV_ID");
                    _Data_6MV_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Data_6MV_ID");
                    OnData_6MV_IDChanged();
                }
            }
        }
        private global::System.Guid _Data_6MV_ID;
        partial void OnData_6MV_IDChanging(global::System.Guid value);
        partial void OnData_6MV_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Delta_6MV
        {
            get
            {
                return _Delta_6MV;
            }
            set
            {
                OnDelta_6MVChanging(value);
                ReportPropertyChanging("Delta_6MV");
                _Delta_6MV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delta_6MV");
                OnDelta_6MVChanged();
            }
        }
        private Nullable<global::System.Double> _Delta_6MV;
        partial void OnDelta_6MVChanging(Nullable<global::System.Double> value);
        partial void OnDelta_6MVChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserData_6MV", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_6MV", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_6MV", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserData_6MV", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserData_6MV", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="QA_Data")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QA_Data : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QA_Data object.
        /// </summary>
        /// <param name="qA_ID">Initial value of the QA_ID property.</param>
        public static QA_Data CreateQA_Data(global::System.Guid qA_ID)
        {
            QA_Data qA_Data = new QA_Data();
            qA_Data.QA_ID = qA_ID;
            return qA_Data;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Blokirovki_vrata
        {
            get
            {
                return _Blokirovki_vrata;
            }
            set
            {
                OnBlokirovki_vrataChanging(value);
                ReportPropertyChanging("Blokirovki_vrata");
                _Blokirovki_vrata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Blokirovki_vrata");
                OnBlokirovki_vrataChanged();
            }
        }
        private global::System.String _Blokirovki_vrata;
        partial void OnBlokirovki_vrataChanging(global::System.String value);
        partial void OnBlokirovki_vrataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QA_ID
        {
            get
            {
                return _QA_ID;
            }
            set
            {
                if (_QA_ID != value)
                {
                    OnQA_IDChanging(value);
                    ReportPropertyChanging("QA_ID");
                    _QA_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("QA_ID");
                    OnQA_IDChanged();
                }
            }
        }
        private global::System.Guid _QA_ID;
        partial void OnQA_IDChanging(global::System.Guid value);
        partial void OnQA_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserQA_Data", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserQA_Data", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserQA_Data", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserQA_Data", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserQA_Data", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="T_P_CorrSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_P_CorrSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_P_CorrSet object.
        /// </summary>
        /// <param name="t_P_ID">Initial value of the T_P_ID property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="t_C">Initial value of the T_C property.</param>
        public static T_P_CorrSet CreateT_P_CorrSet(global::System.Guid t_P_ID, global::System.DateTime data, global::System.Double t_C)
        {
            T_P_CorrSet t_P_CorrSet = new T_P_CorrSet();
            t_P_CorrSet.T_P_ID = t_P_ID;
            t_P_CorrSet.Data = data;
            t_P_CorrSet.T_C = t_C;
            return t_P_CorrSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid T_P_ID
        {
            get
            {
                return _T_P_ID;
            }
            set
            {
                if (_T_P_ID != value)
                {
                    OnT_P_IDChanging(value);
                    ReportPropertyChanging("T_P_ID");
                    _T_P_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("T_P_ID");
                    OnT_P_IDChanged();
                }
            }
        }
        private global::System.Guid _T_P_ID;
        partial void OnT_P_IDChanging(global::System.Guid value);
        partial void OnT_P_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> P_kPa
        {
            get
            {
                return _P_kPa;
            }
            set
            {
                OnP_kPaChanging(value);
                ReportPropertyChanging("P_kPa");
                _P_kPa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("P_kPa");
                OnP_kPaChanged();
            }
        }
        private Nullable<global::System.Double> _P_kPa;
        partial void OnP_kPaChanging(Nullable<global::System.Double> value);
        partial void OnP_kPaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> K_Korr
        {
            get
            {
                return _K_Korr;
            }
            set
            {
                OnK_KorrChanging(value);
                ReportPropertyChanging("K_Korr");
                _K_Korr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("K_Korr");
                OnK_KorrChanged();
            }
        }
        private Nullable<global::System.Double> _K_Korr;
        partial void OnK_KorrChanging(Nullable<global::System.Double> value);
        partial void OnK_KorrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double T_C
        {
            get
            {
                return _T_C;
            }
            set
            {
                OnT_CChanging(value);
                ReportPropertyChanging("T_C");
                _T_C = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("T_C");
                OnT_CChanged();
            }
        }
        private global::System.Double _T_C;
        partial void OnT_CChanging(global::System.Double value);
        partial void OnT_CChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserT_P_CorrSet", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserT_P_CorrSet", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserT_P_CorrSet", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserT_P_CorrSet", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserT_P_CorrSet", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static User CreateUser(global::System.Guid userID)
        {
            User user = new User();
            user.UserID = userID;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Guid _UserID;
        partial void OnUserIDChanging(global::System.Guid value);
        partial void OnUserIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserCalib", "Calib")]
        public EntityCollection<Calib> Calib
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Calib>("Model.UserCalib", "Calib");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Calib>("Model.UserCalib", "Calib", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserData_10MV", "Data_10MV")]
        public EntityCollection<Data_10MV> Data_10MV
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Data_10MV>("Model.UserData_10MV", "Data_10MV");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Data_10MV>("Model.UserData_10MV", "Data_10MV", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserDATA_15MV", "DATA_15MV")]
        public EntityCollection<DATA_15MV> DATA_15MV
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DATA_15MV>("Model.UserDATA_15MV", "DATA_15MV");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DATA_15MV>("Model.UserDATA_15MV", "DATA_15MV", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserT_P_CorrSet", "T_P_CorrSet")]
        public EntityCollection<T_P_CorrSet> T_P_CorrSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_P_CorrSet>("Model.UserT_P_CorrSet", "T_P_CorrSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_P_CorrSet>("Model.UserT_P_CorrSet", "T_P_CorrSet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserData_18MV", "Data_18MV")]
        public EntityCollection<Data_18MV> Data_18MV
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Data_18MV>("Model.UserData_18MV", "Data_18MV");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Data_18MV>("Model.UserData_18MV", "Data_18MV", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserData_6MV", "Data_6MV")]
        public EntityCollection<Data_6MV> Data_6MV
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Data_6MV>("Model.UserData_6MV", "Data_6MV");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Data_6MV>("Model.UserData_6MV", "Data_6MV", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserQA_Data", "QA_Data")]
        public EntityCollection<QA_Data> QA_Data
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<QA_Data>("Model.UserQA_Data", "QA_Data");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<QA_Data>("Model.UserQA_Data", "QA_Data", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
